log error message to stderr too

diff --git a/templates/restic_script_Linux.j2 b/templates/restic_script_Linux.j2
--- a/templates/restic_script_Linux.j2
+++ b/templates/restic_script_Linux.j2
@@ -126,9 +126,12 @@ fi
 {% endif %} | tee {{ backup_output_log }}
 if [[ $? -eq 0 ]]
 then
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ backup_result_log }}
+    # write to both stdout and log
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK: backup $BACKUP_SOURCE completed successfully" | tee -a {{ backup_result_log }}
 else
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ backup_result_log }}
+    # write to log and to stderr
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR: backup $BACKUP_SOURCE completed with errors" >> {{ backup_result_log }}
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR: backup $BACKUP_SOURCE completed with errors" >&2
 fi
 
 {#
@@ -137,7 +140,8 @@ fi
 {{ restic_install_path }}/restic forget --path {{ path(item) }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %} | tee {{ forget_output_log }}
 if [[ $? -eq 0 ]]
 then
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ forget_result_log }}
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK: forget $BACKUP_SOURCE completed successfully" | tee -a {{ forget_result_log }}
 else
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ forget_result_log }}
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR: forget $BACKUP_SOURCE completed with errors" >> {{ forget_result_log }}
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR: forget $BACKUP_SOURCE completed with errors" >&2
 fi
